# pods deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: d-backup-msvc
  labels:
    app: backup-msvc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backup-msvc
  template:
    metadata:
      labels:
        app: backup-msvc
    spec:
      containers:
        - name: backup-msvc
          image: backup-msvc:1.0
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://localhost:5432/postgresdb
            - name: SPRING_RABBITMQ_HOST
              value: lb-rabbitmq-msvc
          resources:
            requests:
              cpu: "400m"
        - name: postgresql
          image: postgres:backup
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: postgresdb
            - name: POSTGRES_USER
              value: postgresuser
            - name: POSTGRES_PASSWORD
              value: postgrespassword
          resources:
            requests:
              cpu: "100m"

---
# load balancer service
apiVersion: v1
kind: Service
metadata:
  name: lb-backup-msvc
spec:
  selector:
    app: backup-msvc
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30000

---
# horizontal pod autoscaler
# apiVersion: autoscaling/v2
# kind: HorizontalPodAutoscaler
# metadata:
#   name: hpa-backup-msvc
# spec:
#   scaleTargetRef:
#     apiVersion: apps/v1
#     kind: Deployment
#     name: d-backup-msvc
#   minReplicas: 1
#   maxReplicas: 2
#   metrics:
#   - type: Resource
#     resource:
#       name: cpu
#       target:
#         type: Utilization
#         averageUtilization: 80
