apiVersion: apps/v1
kind: Deployment
metadata:
  name: d-rabbitmq-msvc
  labels:
    app: rabbitmq-msvc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq-msvc
  template:
    metadata:
      labels:
        app: rabbitmq-msvc
    spec:
      containers:
        - name: rabbitmq-msvc
          image: rabbitmq:3-management-alpine
          ports:
            - containerPort: 5672
            - containerPort: 15672
          resources:
            requests:
              cpu: "200m"

---
apiVersion: v1
kind: Service
metadata:
  name: lb-rabbitmq-msvc
spec:
  selector:
    app: rabbitmq-msvc
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 5672
      targetPort: 5672
