# pods deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: d-reviews-query-msvc
  labels:
    app: reviews-query-msvc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reviews-query-msvc
  template:
    metadata:
      labels:
        app: reviews-query-msvc
    spec:
      containers:
        - name: reviews-query-msvc
          image: reviews-query-msvc:1.0
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://localhost:5432/postgresdb
            - name: SPRING_RABBITMQ_HOST
              value: lb-rabbitmq-msvc
            - name: BACKUP-SERVICE_URL
              value: http://lb-backup-msvc:8080
          resources:
            requests:
              cpu: "400m"
        - name: postgresql
          image: postgres:reviews-query
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: postgresdb
            - name: POSTGRES_USER
              value: postgresuser
            - name: POSTGRES_PASSWORD
              value: postgrespassword
          resources:
            requests:
              cpu: "100m"

---
# load balancer service
apiVersion: v1
kind: Service
metadata:
  name: lb-reviews-query-msvc
spec:
  selector:
    app: reviews-query-msvc
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30005

---
# horizontal pod autoscaler
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: hpa-reviews-query-msvc
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: d-reviews-query-msvc
  minReplicas: 1
  maxReplicas: 2
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 80
